### ISSUE TITLE
👎🏻👎🏻👎🏻👎🏻

### ISSUE THREAD

**Issue by Kopsillom** [ELMERIKH/Keres#1]
can't run in linux pls fix
![Screenshot_2023-12-15-11-35-43-798_com instagram android](https://github.com/ELMERIKH/Keres/assets/86496963/4d718b20-6cfb-4708-9559-aba8e7238cd7)

**Comment by ELMERIKH** [comment]
![téléchargement](https://github.com/ELMERIKH/Keres/assets/96123439/11e8515c-fc1b-4a45-93e4-2af4a74e69e2)

**Comment by ELMERIKH** [comment]
fixed

**Comment by Kopsillom** [comment]
i like this tool, it works on linux now :)
![emotepng](https://github.com/ELMERIKH/Keres/assets/86496963/2517d3f8-2fb8-49f4-8ee0-29b847bf4502)
